# permissions for end users to view nginxoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginxoperator-viewer-role
rules:
- apiGroups:
  - operator.example.com
  resources:
  - nginxoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.example.com
  resources:
  - nginxoperators/status
  verbs:
  - get
